"""Regression tests: reproduce and verify the HTTP 500 on POST /api/v1/agent/events.

These tests send the exact event shape generated by agent v3.0.0 to verify the
backend accepts it successfully.
"""

import json
import pytest
from datetime import datetime, timezone, timedelta
from httpx import AsyncClient

from tests.integration.helpers import enroll_test_host


def _agent_v3_event(
    event_type: str,
    severity: str = "medium",
    description: str | None = None,
    source: str = "auth.log",
    raw_log: str | None = None,
    offset_seconds: int = 0,
) -> dict:
    """Build an event dict matching the exact shape agent v3.0.0 sends.

    Agent sends timestamps as: datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    Agent sends individual event dicts (not wrapped in metadata).
    Agent uses 'default=str' in json.dumps, so datetime objects become strings.
    """
    ts = datetime.now(timezone.utc) + timedelta(seconds=offset_seconds, microseconds=abs(offset_seconds))
    return {
        "event_type": event_type,
        "severity": severity,
        "description": description or f"Agent v3.0.0 test: {event_type}",
        "source": source,
        "raw_log": raw_log or f"agent-v3-test {event_type} from {source}",
        "timestamp": ts.strftime("%Y-%m-%dT%H:%M:%SZ"),
    }


def _agent_v3_batch(events: list[dict]) -> bytes:
    """Serialize like the agent does: json.dumps(data, separators=(',',':'), default=str)"""
    return json.dumps({"events": events}, separators=(",", ":"), default=str).encode()


@pytest.mark.asyncio
async def test_single_v3_event_accepted(client: AsyncClient, admin_client: AsyncClient):
    """Single event in v3.0.0 format is accepted."""
    host_id, api_key = await enroll_test_host(admin_client, "v3-single-host")

    payload = [_agent_v3_event("ssh_login_failure")]
    res = await client.post(
        "/api/v1/agent/events",
        headers={"X-API-Key": api_key},
        json={"events": payload},
    )
    assert res.status_code == 200, f"Expected 200, got {res.status_code}: {res.text}"
    body = res.json()
    assert body["ingested"] == 1
    assert body["errors"] == []


@pytest.mark.asyncio
async def test_43_event_batch_accepted(client: AsyncClient, admin_client: AsyncClient):
    """Batch of 43 events (matching real agent flush) is accepted — this is the exact scenario that returned 500."""
    host_id, api_key = await enroll_test_host(admin_client, "v3-batch-host")

    events = [_agent_v3_event("ssh_login_failure", offset_seconds=-i) for i in range(43)]
    res = await client.post(
        "/api/v1/agent/events",
        headers={"X-API-Key": api_key},
        json={"events": events},
    )
    assert res.status_code == 200, f"Expected 200, got {res.status_code}: {res.text}"
    body = res.json()
    assert body["ingested"] >= 1, f"Expected at least 1 ingested, got {body}"


@pytest.mark.asyncio
async def test_v3_mixed_event_types_batch(client: AsyncClient, admin_client: AsyncClient):
    """Batch with mixed event types matching what a real agent collects."""
    host_id, api_key = await enroll_test_host(admin_client, "v3-mixed-host")

    events = [
        _agent_v3_event("ssh_login_failure", severity="medium"),
        _agent_v3_event("ssh_login_success", severity="low"),
        _agent_v3_event("sudo_usage", severity="low"),
        _agent_v3_event("service_failure", severity="high"),
        _agent_v3_event("service_stop", severity="info"),
        _agent_v3_event("service_start", severity="info"),
    ]
    res = await client.post(
        "/api/v1/agent/events",
        headers={"X-API-Key": api_key},
        json={"events": events},
    )
    assert res.status_code == 200, f"Expected 200, got {res.status_code}: {res.text}"
    body = res.json()
    assert body["ingested"] == 6


@pytest.mark.asyncio
async def test_v3_event_with_raw_log_accepted(client: AsyncClient, admin_client: AsyncClient):
    """Event with long raw_log field (up to 2048 chars) is accepted."""
    host_id, api_key = await enroll_test_host(admin_client, "v3-rawlog-host")

    raw = "A" * 2048
    payload = [_agent_v3_event("ssh_login_failure", raw_log=raw)]
    res = await client.post(
        "/api/v1/agent/events",
        headers={"X-API-Key": api_key},
        json={"events": payload},
    )
    assert res.status_code == 200, f"Expected 200, got {res.status_code}: {res.text}"


@pytest.mark.asyncio
async def test_v3_event_raw_body_serialization_matches_agent(client: AsyncClient, admin_client: AsyncClient):
    """Verify the exact bytes the agent sends are accepted by the backend."""
    host_id, api_key = await enroll_test_host(admin_client, "v3-bytes-host")

    events = [_agent_v3_event("ssh_login_failure")]
    body_bytes = _agent_v3_batch(events)

    res = await client.post(
        "/api/v1/agent/events",
        headers={
            "X-API-Key": api_key,
            "Content-Type": "application/json",
        },
        content=body_bytes,
    )
    assert res.status_code == 200, f"Expected 200, got {res.status_code}: {res.text}"


@pytest.mark.asyncio
async def test_v3_full_flush_cycle(client: AsyncClient, admin_client: AsyncClient):
    """Simulate the exact flush cycle: 43 events, then verify they appear in the DB."""
    host_id, api_key = await enroll_test_host(admin_client, "v3-flush-host")

    events = [_agent_v3_event("ssh_login_failure", offset_seconds=-i) for i in range(43)]
    res = await client.post(
        "/api/v1/agent/events",
        headers={"X-API-Key": api_key},
        json={"events": events},
    )
    assert res.status_code == 200, f"Expected 200, got {res.status_code}: {res.text}"

    # Verify events appear in the events listing
    events_res = await admin_client.get(
        "/api/v1/events",
        params={"host_id": host_id, "page_size": 50},
    )
    assert events_res.status_code == 200, events_res.text
    items = events_res.json()["items"]
    assert len(items) >= 1, f"Expected at least 1 event in DB, got {len(items)}"
    assert any(e["event_type"] == "ssh_login_failure" for e in items)


@pytest.mark.asyncio
async def test_v3_500_regression_with_sequential_requests(client: AsyncClient, admin_client: AsyncClient):
    """Reproduce the exact failure: multiple sequential POST /api/v1/agent/events.

    The agent sends heartbeat, then events, then metrics in sequence.
    This test sends events repeatedly to catch intermittent 500s.
    """
    host_id, api_key = await enroll_test_host(admin_client, "v3-seq-host")

    # Send heartbeat first (like the real agent does)
    hb_res = await client.post(
        "/api/v1/agent/heartbeat",
        headers={"X-API-Key": api_key},
        json={"agent_version": "3.0.0", "agent_hash": "test-hash"},
    )
    assert hb_res.status_code == 200, hb_res.text

    # Send 5 batches of 10 events (simulating the agent's 10-second log collection cycle)
    for batch_idx in range(5):
        events = [
            _agent_v3_event("ssh_login_failure", offset_seconds=-(batch_idx * 10 + i))
            for i in range(10)
        ]
        res = await client.post(
            "/api/v1/agent/events",
            headers={"X-API-Key": api_key},
            json={"events": events},
        )
        assert res.status_code == 200, (
            f"Batch {batch_idx}: Expected 200, got {res.status_code}: {res.text}"
        )


@pytest.mark.asyncio
async def test_mixed_metric_in_events_batch_does_not_500(client: AsyncClient, admin_client: AsyncClient):
    """Regression: metrics accidentally buffered as events used to 500 the whole batch."""
    host_id, api_key = await enroll_test_host(admin_client, "v3-mixed-metric-host")
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    payload = {
        "events": [
            _agent_v3_event("ssh_login_failure"),
            {
                "cpu_percent": 11.0,
                "memory_percent": 22.0,
                "disk_percent": 33.0,
                "recorded_at": ts,
            },
        ]
    }
    res = await client.post(
        "/api/v1/agent/events",
        headers={"X-API-Key": api_key},
        json=payload,
    )
    assert res.status_code == 200, res.text
    body = res.json()
    assert body["ingested"] == 1
    assert any("metric payload" in err for err in body["errors"])


@pytest.mark.asyncio
async def test_invalid_source_ip_metadata_is_ingested(client: AsyncClient, admin_client: AsyncClient):
    host_id, api_key = await enroll_test_host(admin_client, "v3-bad-ip-host")
    event = _agent_v3_event("ssh_login_failure")
    event["metadata"] = {"source_ip": "not-an-ip"}
    res = await client.post(
        "/api/v1/agent/events",
        headers={"X-API-Key": api_key},
        json={"events": [event]},
    )
    assert res.status_code == 200, res.text
    assert res.json()["ingested"] == 1


@pytest.mark.asyncio
async def test_long_source_is_truncated_not_500(client: AsyncClient, admin_client: AsyncClient):
    host_id, api_key = await enroll_test_host(admin_client, "v3-long-source-host")
    event = _agent_v3_event("ssh_login_failure")
    event["source"] = "/" + ("a" * 80)
    res = await client.post(
        "/api/v1/agent/events",
        headers={"X-API-Key": api_key},
        json={"events": [event]},
    )
    assert res.status_code == 200, res.text
    assert res.json()["ingested"] == 1


@pytest.mark.asyncio
async def test_malformed_events_body_is_422_not_500(client: AsyncClient, admin_client: AsyncClient):
    host_id, api_key = await enroll_test_host(admin_client, "v3-bad-json-host")
    res = await client.post(
        "/api/v1/agent/events",
        headers={"X-API-Key": api_key, "Content-Type": "application/json"},
        content=b"{not json",
    )
    assert res.status_code == 422, res.text


@pytest.mark.asyncio
async def test_empty_events_array_does_not_500(client: AsyncClient, admin_client: AsyncClient):
    host_id, api_key = await enroll_test_host(admin_client, "v3-empty-host")
    res = await client.post(
        "/api/v1/agent/events",
        headers={"X-API-Key": api_key},
        json={"events": []},
    )
    assert res.status_code in (200, 422), res.text
    assert res.status_code != 500
